medclinic/apps/cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:service_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:item_id>/", views.cart_remove, name="cart_remove"),
]

medclinic/apps/services/urls.py
from django.urls import path
from . import views

app_name = 'services'

urlpatterns = [
    path("drips/", views.drip_list, name="drip_list"), # мини-админка
    path("drips/admin/", views.drip_admin, name="drip_admin"),
    path("drips/add/", views.drip_add, name="drip_add"),
    path("drips/<int:pk>/edit/", views.drip_edit, name="drip_edit"),
    path("drips/<int:pk>/delete/", views.drip_delete, name="drip_delete"),
]

medclinic/apps/users/urls.py
from .views import admin_profile, profile, user_logout
from django.urls import path
from .views import password_reset_confirm, register, user_login, password_reset_request

app_name = 'users'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path("logout/", user_logout, name="logout"),
    path('password/reset/', password_reset_request, name='password_reset_request'),
    path('password/reset/confirm/<uidb64>/<token>/', password_reset_confirm, name='password_reset_confirm'),
    path('profile/', profile, name='profile'),
    # path('profile/update_phone/', update_phone, name='update_phone'),
    path('admin_profile/', admin_profile, name='admin_profile')
]

medclinic/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),  # Главная страница
    path('users/', include('users.urls', namespace='users')),  # Префикс для users
    path("services/", include("services.urls", namespace='services')),
    path("cart/", include("cart.urls", namespace='cart')),
    path("orders/", include("orders.urls", namespace='orders')),
]

medclinic/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{{ title|default:"Falimy DOC" }}{% endblock %}</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% comment %} <link rel="stylesheet" href="{% static 'css/main.css' %}"> {% endcomment %}
    
    {% block extra_css %}{% endblock %}
</head>
<body>
<header class="header">
    <div class="header__container container">
        <a href="/" class="header__logo-link">
            <div class="header__logo">Family <span class="header__logo--dot">:</span><span class="header__logo--sub">DOC</span><span class="header__logo--slogan">Всегда рядом</span></div>
            <div class="header__logo--info">Медицинская клиника-партнер НИИ Эпидемиологии и Роспотребнадзора CMD </div>
        </a>
        <div><p class="contact">+7 (903) 224 6322</p></div>
        <nav class="header__nav header__nav--desktop" aria-label="Главное меню">
            <ul class="nav-list">
                <li class="nav-item"><a href="{% url 'users:admin_profile' %}" class="nav-link">О нас</a></li>
                <li class="nav-item nav-item--has-sub">
                    <a href="#" class="nav-link">Услуги и цены</a>
                    <ul class="nav-submenu">
                        <li class="nav-submenu__item"><a href="/" class="nav-submenu__link"><span>Каталог анализов</span></a></li>
                        <li class="nav-submenu__item"><a href="{% url 'services:drip_list' %}" class="nav-submenu__link"><span>Каталог капельниц</span></a></li>
                        <li class="nav-submenu__item"><a href="{% url 'services:drip_list' %}" class="nav-submenu__link"><span>Запись к врачу</span></a></li>
                    </ul>
                </li>
                <li class="nav-item"><a href="#subscriptions-section__anchor" class="nav-link">Подписки</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Бизнес-партнерам</a></li>
                <li class="nav-item"><a href="#" class="nav-link">FAQ</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Контакты</a></li>
                
                {% if user.is_authenticated %}
                    <li class="nav-item"><a href="{% url 'users:profile' %}" class="nav-link">Личный кабинет</a></li>
                {% else %}
                    <li class="nav-item"><a href="{% url 'users:login' %}" class="nav-link">Личный кабинет</a></li>
                {% endif %}
                {% comment %} <li class="nav-item"><a href="{% url 'cart:cart_detail' %}" class="nav-link header__action-link--cart" aria-label="Корзина"><i class="fa fa-shopping-cart"></i></a></li> {% endcomment %}
            </ul>
        </nav>
        
        <div class="header__actions">
            <a href="{% url 'cart:cart_detail' %}" class="header__action-btn header__action-btn--cart" aria-label="Корзина"><i class="fa fa-shopping-cart"></i></a>
            <button id="burger-btn" class="header__action-btn header__action-btn--menu" aria-label="Открыть меню" aria-expanded="false">
                <svg class="hamburger-icon" viewBox="0 0 100 100" width="44">
                    <path class="hamburger-icon__line--top" d="m 70,33 h -40 c 0,0 -6,1.368796 -6,8.5 0,7.131204 6,8.5013 6,8.5013 l 20,-0.0013" />
                    <path class="hamburger-icon__line--middle" d="m 70,50 h -40" />
                    <path class="hamburger-icon__line--bottom" d="m 69.575405,67.073826 h -40 c -5.592752,0 -6.873604,-9.348582 1.371031,-9.348582 8.244634,0 19.053564,21.797129 19.053564,12.274756 l 0,-40" />
                </svg>
            </button>
        </div>
    </div>
</header>

<div id="search-modal" class="modal" role="dialog" aria-modal="true">
    <div class="modal__content">
        <span class="modal__close-btn" aria-label="Закрыть">&times;</span>
        <input type="text" id="search-input" class="modal__input" placeholder="Поиск анализов..." required>
        <button id="search-submit" class="modal__submit-btn">Найти</button>
    </div>
</div>

<nav id="mobile-menu" class="mobile-menu" aria-label="Мобильное меню">
    <div class="mobile-menu__content">
        <ul class="mobile-menu__list">
            <li class="mobile-menu__item"><a href="/tests" class="mobile-menu__link">Запись к врачу</a></li>
            <li class="mobile-menu__item"><a href="/tests" class="mobile-menu__link">Результаты анализов</a></li>
             <li class="mobile-menu__item mobile-menu__item--has-sub">
                <a href="#" class="mobile-menu__link mobile-menu__link--accordion">Услуги и цены</a>
                <ul class="mobile-menu__submenu">
                    <li class="mobile-menu__submenu-item"><a href="/" class="mobile-menu__submenu-link">Каталог анализов</a></li>
                    <li class="mobile-menu__submenu-item"><a href="{% url 'services:drip_list' %}" class="mobile-menu__submenu-link">Каталог капельниц</a></li>
                    
                </ul>
            </li>
            <li class="mobile-menu__item mobile-menu__item--has-sub">
                <a href="#" class="mobile-menu__link mobile-menu__link--accordion">Подписки</a>
                <ul class="mobile-menu__submenu">
                    <li class="mobile-menu__submenu-item"><a href="/" class="mobile-menu__submenu-link">Дежурный врач</a></li>
                    <li class="mobile-menu__submenu-item"><a href="/" class="mobile-menu__submenu-link">Light</a></li>
                    <li class="mobile-menu__submenu-item"><a href="/" class="mobile-menu__submenu-link">Special</a></li>
                </ul>
            </li>
            
            
            <li class="mobile-menu__item"><a href="/tests" class="mobile-menu__link">Бизнес-партнерам</a></li>
            <li class="mobile-menu__item"><a href="/tests" class="mobile-menu__link">FAQ</a></li>
            <li class="mobile-menu__item"><a href="/tests" class="mobile-menu__link">О нас</a></li>
            <li class="mobile-menu__item"><a href="{% url 'users:admin_profile' %}" class="mobile-menu__link">Админка</a></li>
        </ul>
        <div class="mobile-menu__footer">
            {% if user.is_authenticated %}
                <a href="{% url 'users:profile' %}" class="mobile-menu__profile-link"><i class="fa fa-user-circle"></i> {{ user.last_name }} {{ user.first_name }}</a>
            {% else %}
                <a href="{% url 'users:login' %}" class="mobile-menu__profile-link"><i class="fa fa-user"></i> Войти</a>
            {% endif %}
            <span>+7 (909) 999-99-99</span>
        </div>
    </div>
</nav>

<div id="overlay" class="overlay"></div>

<main class="main-content-padding main__container">
    {% block content %}{% endblock %}
</main>
<svg class="footer-wave" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
    <path fill="#fff" fill-opacity="1" d="M0,192L48,186.7C96,181,192,171,288,181.3C384,192,480,224,576,218.7C672,213,768,171,864,170.7C960,171,1056,213,1152,229.3C1248,245,1344,235,1392,230.7L1440,224L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z"></path>
</svg>
<footer class="footer">
    <div class="footer__container container">
        <div class="footer__section">
            <h4 class="footer__heading">О нас</h4>
            <ul class="footer__list">
                <li class="footer__list-item"><a href="#" class="footer__link">Наша миссия</a></li>
                <li class="footer__list-item"><a href="#" class="footer__link">Команда</a></li>
            </ul>
        </div>
        <div class="footer__section">
            <h4 class="footer__heading">Услуги</h4>
            <ul class="footer__list">
                <li class="footer__list-item"><a href="#" class="footer__link">Консультации</a></li>
                <li class="footer__list-item"><a href="#" class="footer__link">Анализы</a></li>
            </ul>
        </div>
        <div class="footer__section">
            <h4 class="footer__heading">Контакты</h4>
            <ul class="footer__list">
                <li class="footer__list-item"><a href="/" class="footer__link">+1 234 567 89</a></li>
                <li class="footer__list-item"><a href="/" class="footer__link">info@familydoc.com</a></li>
            </ul>
        </div>
        <div class="footer__section footer__section--social">
            <h4 class="footer__heading">Мы в соцсетях</h4>
            <div class="footer__social-links">
                <a href="#" class="footer__social-link"><i class="fab fa-facebook-f"></i></a>
                <a href="#" class="footer__social-link"><i class="fab fa-twitter"></i></a>
                <a href="#" class="footer__social-link"><i class="fab fa-instagram"></i></a>
            </div>
        </div>
    </div>
</footer>
<script src="{% static 'js/utils/scrollbar-width.js' %}"></script>
<script src="{% static 'js/components/hero-slider.js' %}"></script>
<script src="{% static 'js/components/popular-slider.js' %}"></script>
<script src="{% static 'js/components/accordion.js' %}"></script>
<script src="{% static 'js/components/chat-popup.js' %}"></script>
<script src="{% static 'js/components/mobile-menu.js' %}"></script>
<script src="{% static 'js/components/cart-counter.js' %}"></script>
<script src="{% static 'js/components/desktop-nav.js' %}"></script>
<script src="{% static 'js/components/search-modal.js' %}"></script>
<script src="{% static 'js/app.js' %}"></script>

{% block extra_js %}{% endblock %}
</body>
</html>